name: air_tickets_repository
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  retrofit: ^4.1.0
  json_annotation: ^4.9.0
  dio: ^5.4.3+1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0